In [2]:
import io 
import sqlite3 
import pandas as pd

conn = sqlite3.connect('tp1.db') 
cursor = conn.cursor()

#f = io.open('despesas_publicas_tp1.sql', 'r') 
#sql = f.read() 
#cursor.executescript(sql)

1.  Liste todos os códigos e nomes de funções da subfunção que possui o maior número de funções.

In [5]:
df = pd.read_sql_query("SELECT COD_FUNCAO, NOME_FUNCAO "+
                       "FROM (DETALHAMENTO_FUNCAO NATURAL JOIN FUNCAO) "+
                       "WHERE COD_SUBFUNCAO = (SELECT COD_SUBFUNCAO "+
                                               "FROM DETALHAMENTO_FUNCAO "+
                                               "GROUP BY COD_SUBFUNCAO "+
                                               "ORDER BY COUNT(COD_FUNCAO) DESC LIMIT 1);", conn)
df

   COD_FUNCAO        NOME_FUNCAO
0           5    Defesa nacional
1           6  Segurança pública
2          26         Transporte

4. Liste o mês e ano, modalidade, programa de governo e valor de todas as despesas do órgão Ministério da Educação no primeiro semestre de 2018.

In [22]:
df = pd.read_sql_query("SELECT MES_DESPESA, ANO_DESPESA, MODALIDADE_DESPESA, NOME_PROGRAMA_GOVERNO, VALOR_DESPESA "+
                       "FROM (DESPESA_PUBLICA NATURAL JOIN PROGRAMA_GOVERNO) "+
                       "WHERE COD_DESPESA IN (SELECT COD_DESPESA "+
                                           "FROM (DESPESA_PUBLICA NATURAL JOIN ORGAO) "+
                                           "WHERE NOME_ORGAO = 'Ministério da Educação' "+
                                           "AND ANO_DESPESA = 2018 AND MES_DESPESA <= 6);", conn)
df

,MES_DESPESA,ANO_DESPESA,MODALIDADE_DESPESA,NOME_PROGRAMA_GOVERNO,VALOR_DESPESA
0,1,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
1,2,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
2,3,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
3,4,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
4,5,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
5,6,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
6,1,2018,APLICACOES DIRETAS - OPER.INTRA-ORCAMENTARIAS,VIVER SEM LIMITE,0.0
7,6,2018,APLICACOES DIRETAS - OPER.INTRA-ORCAMENTARIAS,VIVER SEM LIMITE,0.0
8,1,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
9,2,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
10,3,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
11,4,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
12,5,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
13,6,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
14,2,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
15,5,2018,Transferências a Estados e ao Distrito Federal,VIVER SEM LIMITE,0.0
16,5,2018,Transferências a Municípios,VIVER SEM LIMITE,0.0
17,2,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
18,3,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
19,6,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
20,5,2018,Reserva de Contingência,VIVER SEM LIMITE,0.0
21,1,2018,Reserva de Contingência,MELHOR EM CASA,0.0
22,2,2018,Reserva de Contingência,MELHOR EM CASA,0.0
23,1,2018,Reserva de Contingência,REDE CEGONHA,1210.0
24,2,2018,Reserva de Contingência,REDE CEGONHA,0.0
25,3,2018,Reserva de Contingência,REDE CEGONHA,0.0
26,4,2018,Reserva de Contingência,REDE CEGONHA,0.0
27,5,2018,Reserva de Contingência,REDE CEGONHA,0.0
28,6,2018,Reserva de Contingência,REDE CEGONHA,0.0
29,1,2018,APLICACOES DIRETAS - OPER.INTRA-ORCAMENTARIAS,CONTROLE DO CANCER,0.0
...,...,...,...,...,...
123,2,2018,Reserva de Contingência,BRASIL SEM MISERIA,0.0
124,3,2018,Reserva de Contingência,BRASIL SEM MISERIA,0.0
125,4,2018,Reserva de Contingência,BRASIL SEM MISERIA,0.0
126,5,2018,Reserva de Contingência,BRASIL SEM MISERIA,0.0
127,1,2018,Reserva de Contingência,BRASIL SEM MISERIA,0.0
128,3,2018,Reserva de Contingência,BRASIL SEM MISERIA,0.0
129,4,2018,Reserva de Contingência,BRASIL SEM MISERIA,0.0
130,5,2018,Reserva de Contingência,BRASIL SEM MISERIA,0.0
131,6,2018,Reserva de Contingência,BRASIL SEM MISERIA,0.0
132,2,2018,Reserva de Contingência,REGULARIZACAO FUNDIARIA,0.0
133,1,2018,APLICACOES DIRETAS - OPER.INTRA-ORCAMENTARIAS,REGULARIZACAO FUNDIARIA,0.0
134,1,2018,Reserva de Contingência,REGULARIZACAO FUNDIARIA,0.0
135,1,2018,Reserva de Contingência,MAIS MEDICOS,0.0
136,2,2018,Reserva de Contingência,MAIS MEDICOS,0.0
137,3,2018,Reserva de Contingência,MAIS MEDICOS,0.0
138,4,2018,Reserva de Contingência,MAIS MEDICOS,0.0
139,5,2018,Reserva de Contingência,MAIS MEDICOS,0.0
140,6,2018,Reserva de Contingência,MAIS MEDICOS,0.0
141,1,2018,Reserva de Contingência,MAIS MEDICOS,0.0
142,2,2018,Reserva de Contingência,MAIS MEDICOS,0.0
143,3,2018,Reserva de Contingência,MAIS MEDICOS,0.0
144,4,2018,Reserva de Contingência,MAIS MEDICOS,0.0
145,5,2018,Reserva de Contingência,MAIS MEDICOS,0.0
146,6,2018,Reserva de Contingência,MAIS MEDICOS,0.0
147,1,2018,Reserva de Contingência,MAIS MEDICOS,0.0
148,2,2018,Reserva de Contingência,MAIS MEDICOS,0.0
149,3,2018,Reserva de Contingência,MAIS MEDICOS,0.0
150,4,2018,Reserva de Contingência,MAIS MEDICOS,0.0
151,5,2018,Reserva de Contingência,MAIS MEDICOS,0.0
152,6,2018,Reserva de Contingência,MAIS MEDICOS,0.0

5. Liste o código e nome dos órgãos que possuíram os 5 maiores valores de despesas totais nas funções de educação e saúde durante o ano de 2018.

In [21]:
df = pd.read_sql_query("SELECT COD_ORGAO, NOME_ORGAO "+
                       "FROM (ORGAO NATURAL JOIN DESPESA_PUBLICA NATURAL JOIN DETALHAMENTO_FUNCAO NATURAL JOIN FUNCAO) "+
                       "WHERE (NOME_FUNCAO = 'Educação' OR NOME_FUNCAO = 'Saúde') AND ANO_DESPESA = 2018 "+
                       "GROUP BY COD_ORGAO "+
                       "ORDER BY SUM(VALOR_DESPESA) DESC LIMIT 5;", conn)
df

   COD_ORGAO                                     NOME_ORGAO
0      52000                           Ministério da Defesa
1      26000                         Ministério da Educação
2      36000                            Ministério da Saúde
3      24000  Ministério da Ciência, Tecnologia, Inovações
4      30000      Ministério da Justiça e Segurança Pública

6. Liste todos os nomes de funções e subfunções das despesas públicas dos últimos 5 meses de 2018 e seus respectivos valores totais, ordenando de forma decrescente pelo valor.

In [20]:
df = pd.read_sql_query("SELECT NOME_FUNCAO, NOME_SUBFUNCAO, SUM(VALOR_DESPESA) AS DESPESA_TOTAL "+
                       "FROM (DESPESA_PUBLICA NATURAL JOIN DETALHAMENTO_FUNCAO NATURAL JOIN FUNCAO NATURAL JOIN SUBFUNCAO) "+
                        "WHERE ANO_DESPESA = 2018 AND MES_DESPESA >= 8 "+
                        "GROUP BY NOME_FUNCAO, NOME_SUBFUNCAO "+
                        "ORDER BY SUM(VALOR_DESPESA) DESC;", conn)
df

,NOME_FUNCAO,NOME_SUBFUNCAO,DESPESA_TOTAL
0,Educação,Educação básica,334126.70
1,Assistência social,Alimentação e nutrição,100373.55
2,Educação,Ensino profissional,7011.38
3,Educação,Ensino superior,2400.00
4,Saúde,Atenção básica,1000.00
5,Agricultura,Difusão do conhecimento científico e tecnológico,0.00
6,Agricultura,Promoção da produção agropecuária,0.00
7,Assistência social,Assistência comunitária,0.00
8,Assistência social,Educação infantil,0.00
9,Assistência social,Normatização e fiscalização,0.00
10,Assistência social,Saneamento básico rural,0.00
11,Assistência social,Tecnologia da informação,0.00
12,Ciência e Tecnologia,Desenvolvimento científico,0.00
13,Ciência e Tecnologia,Desenvolvimento tecnológico e engenharia,0.00
14,Defesa nacional,Administração geral,0.00
15,Defesa nacional,Defesa terrestre,0.00
16,Direitos da cidadania,Assistência ao portador de deficiência,0.00
17,Direitos da cidadania,Custódia e reintegração social,0.00
18,Direitos da cidadania,"Direitos individuais, coletivos e difusos",0.00
19,Educação,Assistência hospitalar e ambulatorial,0.00
20,Encargos especiais,Outros encargos especiais,0.00
21,Essencial à justiça,Comunicação social,0.00
22,Gestão ambiental,Recursos hídricos,0.00
23,Indústria,Promoção comercial,0.00
24,Organização agrária,Extensão rural,0.00
25,Organização agrária,Normatização e fiscalização,0.00
26,Organização agrária,Ordenamento territorial,0.00
27,Organização agrária,Reforma agrária,0.00
28,Saúde,Assistência hospitalar e ambulatorial,0.00
29,Saúde,Formação de recursos humanos,0.00
30,Segurança pública,Defesa civil,0.00
31,Segurança pública,Informação e inteligência,0.00
32,Segurança pública,Policiamento,0.00
33,Transporte,Administração geral,0.00
34,Urbanismo,Assistência comunitária,0.00

7. Liste os programas de governo e a quantidade de órgãos governamentais distintos envolvidos nas despesas públicas desses programas. Nesta consulta, desconsidere valores de despesa negativos ou iguais a zero no período.

In [12]:
df = pd.read_sql_query("SELECT NOME_PROGRAMA_GOVERNO, COUNT(DISTINCT COD_ORGAO) AS QTDE_ORGAOS "+
                       "FROM (PROGRAMA_GOVERNO NATURAL JOIN DESPESA_PUBLICA) "+
                       "WHERE VALOR_DESPESA > 0 "+
                       "GROUP BY COD_PROGRAMA_GOVERNO;", conn)
df

     NOME_PROGRAMA_GOVERNO  QTDE_ORGAOS
0             REDE CEGONHA            1
1       CONTROLE DO CANCER            1
2                     ENEM            2
3                 PRONATEC            1
4       BRASIL SEM MISERIA            3
5  REGULARIZACAO FUNDIARIA            1
6             MAIS MEDICOS            2

8. Liste os nomes das subfunções das despesas públicas envolvidas para cada órgão governamental, apenas nos casos em que o valor total das despesas excedeu 10 mil reais. Sua consulta deve retornar o nome do órgão, a subfunção da despesa, a quantidade de entradas de despesas públicas e o valor total dessas despesas.

In [23]:
df = pd.read_sql_query("SELECT NOME_ORGAO, NOME_SUBFUNCAO, COUNT (VALOR_DESPESA) AS QTDE_DESPESAS, SUM(VALOR_DESPESA) AS TOTAL_DESPESAS "+ 
                       "FROM (SUBFUNCAO NATURAL JOIN DETALHAMENTO_FUNCAO NATURAL JOIN DESPESA_PUBLICA NATURAL JOIN ORGAO) "+
                       "GROUP BY NOME_ORGAO, NOME_SUBFUNCAO HAVING SUM(VALOR_DESPESA) > 10000;", conn)
df

,NOME_ORGAO,NOME_SUBFUNCAO,QTDE_DESPESAS,TOTAL_DESPESAS
0,"Ministério da Agricultura, Pecuária e Abastec",Alimentação e nutrição,23,81123.55
1,Ministério da Defesa,Alimentação e nutrição,12,19250.00
2,Ministério da Defesa,Educação básica,12,334126.70
3,Ministério da Educação,Ensino profissional,33,60262.46
4,Ministério da Saúde,Assistência hospitalar e ambulatorial,138,38971.19
5,Ministério da Saúde,Atenção básica,62,12000.00
6,Ministério do Desenvolvimento Social,Assistência comunitária,88,219668.07
7,Ministério do Desenvolvimento Social,Tecnologia da informação,14,58918.28

12. πNOME_FUNCAO,VALOR_DESPESA(FUNCAO ⋈ DETALHAMENTO_FUNCAO ⋈ DESPESA_PUBLICA)

In [24]:
df = pd.read_sql_query("SELECT DISTINCT NOME_FUNCAO, VALOR_DESPESA "+
                       "FROM (FUNCAO NATURAL JOIN DETALHAMENTO_FUNCAO NATURAL JOIN DESPESA_PUBLICA);", conn)
df

              NOME_FUNCAO  VALOR_DESPESA
0     Essencial à justiça           0.00
1         Defesa nacional           0.00
2       Segurança pública           0.00
3      Assistência social           0.00
4      Assistência social       58918.28
5      Assistência social        8215.70
6      Assistência social      219668.07
7      Assistência social           3.42
8      Assistência social       19250.00
9      Assistência social       81120.13
10                  Saúde           0.00
11                  Saúde        1000.00
12                  Saúde       11000.00
13                  Saúde        1210.00
14                  Saúde       38971.19
15               Trabalho           0.00
16               Educação           0.00
17               Educação         385.38
18               Educação         726.00
19               Educação        2000.00
20               Educação        5000.00
21               Educação        5900.00
22               Educação       18178.00
23               Educação       28073.08
24               Educação        2400.00
25               Educação         135.36
26               Educação      334126.70
27  Direitos da cidadania           0.00
28              Urbanismo           0.00
29       Gestão ambiental           0.00
30   Ciência e Tecnologia           0.00
31            Agricultura           0.00
32    Organização agrária           0.00
33    Organização agrária        1497.26
34              Indústria           0.00
35             Transporte           0.00
36     Encargos especiais           0.00

13.  πMODALIDADE_DESPESA,VALOR_DESPESA,NOME_ORGAO(ORGAO ⋈ σMODALIDADE_DESPESA='Reserva de Contingência'(DESPESA_PUBLICA))

In [11]:
df = pd.read_sql_query("SELECT  DISTINCT MODALIDADE_DESPESA, VALOR_DESPESA, NOME_ORGAO "+
                       "FROM (ORGAO NATURAL JOIN (SELECT * FROM DESPESA_PUBLICA "+
                       "WHERE MODALIDADE_DESPESA = 'Reserva de Contingência'));", conn)
df

,MODALIDADE_DESPESA,VALOR_DESPESA,NOME_ORGAO
0,Reserva de Contingência,0.00,Presidência da República
1,Reserva de Contingência,0.00,"Ministério da Agricultura, Pecuária e Abastec"
2,Reserva de Contingência,8215.70,"Ministério da Agricultura, Pecuária e Abastec"
3,Reserva de Contingência,3.42,"Ministério da Agricultura, Pecuária e Abastec"
4,Reserva de Contingência,81120.13,"Ministério da Agricultura, Pecuária e Abastec"
5,Reserva de Contingência,1497.26,"Ministério da Agricultura, Pecuária e Abastec"
6,Reserva de Contingência,0.00,"Ministério da Ciência, Tecnologia, Inovações"
7,Reserva de Contingência,0.00,Ministério da Fazenda
8,Reserva de Contingência,0.00,Ministério da Educação
9,Reserva de Contingência,1210.00,Ministério da Educação
10,Reserva de Contingência,135.36,Ministério da Educação
11,Reserva de Contingência,2000.00,Ministério da Educação
12,Reserva de Contingência,18178.00,Ministério da Educação
13,Reserva de Contingência,28073.08,Ministério da Educação
14,Reserva de Contingência,385.38,Ministério da Educação
15,Reserva de Contingência,5900.00,Ministério da Educação
16,Reserva de Contingência,2400.00,Ministério da Educação
17,Reserva de Contingência,0.00,Ministério da Justiça e Segurança Pública
18,Reserva de Contingência,0.00,Ministério das Relações Exteriores
19,Reserva de Contingência,0.00,Ministério da Saúde
20,Reserva de Contingência,38971.19,Ministério da Saúde
21,Reserva de Contingência,11000.00,Ministério da Saúde
22,Reserva de Contingência,1000.00,Ministério da Saúde
23,Reserva de Contingência,0.00,"Ministério dos Transportes, Portos e Aviação"
24,Reserva de Contingência,0.00,Ministério do Meio Ambiente
25,Reserva de Contingência,0.00,Ministério da Defesa
26,Reserva de Contingência,334126.70,Ministério da Defesa
27,Reserva de Contingência,19250.00,Ministério da Defesa
28,Reserva de Contingência,0.00,Ministério da Integração Nacional
29,Reserva de Contingência,0.00,Ministério do Desenvolvimento Social
30,Reserva de Contingência,58918.28,Ministério do Desenvolvimento Social
31,Reserva de Contingência,0.00,Ministério dos Direitos Humanos

14. πVALOR_DESPESA,NOME_PROGRAMA_GOVERNO(DESPESA_PUBLICA ⋈ σNOME_PROGRAMA_GOVERNO='ENEM'(PROGRAMA_GOVERNO))

In [14]:
df = pd.read_sql_query("SELECT DISTINCT VALOR_DESPESA, NOME_PROGRAMA_GOVERNO "+
                       "FROM (DESPESA_PUBLICA NATURAL JOIN (SELECT * FROM PROGRAMA_GOVERNO "+
                       "WHERE NOME_PROGRAMA_GOVERNO = 'ENEM'));", conn)
df

   VALOR_DESPESA NOME_PROGRAMA_GOVERNO
0           0.00                  ENEM
1         135.36                  ENEM
2      334126.70                  ENEM

15.  πNOME_PROGRAMA_GOVERNO,QTD_ORGAOS_SUBORDINADOS,VALOR_DESPESA(DESPESA_PUBLICA ⋈ σNOME_ORGAO='Ministério da Educação'(ORGAO) ⋈ PROGRAMA GOVERNO)

In [15]:
df = pd.read_sql_query("SELECT DISTINCT NOME_PROGRAMA_GOVERNO, QTD_ORGAOS_SUBORDINADOS, VALOR_DESPESA "+
                       "FROM (DESPESA_PUBLICA NATURAL JOIN (SELECT * FROM ORGAO "+
                       "WHERE NOME_ORGAO = 'Ministério da Educação') "+
                       "NATURAL JOIN PROGRAMA_GOVERNO);", conn)
df

       NOME_PROGRAMA_GOVERNO  QTD_ORGAOS_SUBORDINADOS  VALOR_DESPESA
0           VIVER SEM LIMITE                      104           0.00
1             MELHOR EM CASA                      104           0.00
2               REDE CEGONHA                      104        1210.00
3               REDE CEGONHA                      104           0.00
4         CONTROLE DO CANCER                      104           0.00
5     CIENCIA SEM FRONTEIRAS                      104           0.00
6                       ENEM                      104           0.00
7                       ENEM                      104         135.36
8               PROVA BRASIL                      104           0.00
9                   PRONATEC                      104           0.00
10                  PRONATEC                      104        5000.00
11                  PRONATEC                      104         726.00
12                  PRONATEC                      104        2000.00
13                  PRONATEC                      104       18178.00
14                  PRONATEC                      104       28073.08
15                  PRONATEC                      104         385.38
16                  PRONATEC                      104        5900.00
17      GESTAO AEROPORTUARIA                      104           0.00
18        DESASTRES NATURAIS                      104           0.00
19          CADEIAS PUBLICAS                      104           0.00
20  TERRITORIOS DA CIDADANIA                      104           0.00
21  CRACK, E POSSIVEL VENCER                      104           0.00
22        BRASIL SEM MISERIA                      104           0.00
23   REGULARIZACAO FUNDIARIA                      104           0.00
24              MAIS MEDICOS                      104           0.00
25              MAIS MEDICOS                      104        2400.00